// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05.06.2025, 10:42:33
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/plugins/**/*.{js,ts,mjs}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/composables/**/*.{js,ts,mjs}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/utils/**/*.{js,ts,mjs}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/narim/OneDrive/Рабочий стол/nuxtjs-app/my-app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;